import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Intro from "../components/Intro";
import Middle from "../components/Scroller";
import Scroller from "../components/Scroller";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Lone Star Roofing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <Intro />
      <Scroller />
    </div>
  );
}
